<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personnel extends \App\Entity\Personnel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'poste', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'entreprise', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'conteneure', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'travaillerPersonnels'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'poste', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'entreprise', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'conteneure', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Personnel' . "\0" . 'travaillerPersonnels'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personnel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(string $sexe): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(string $telephone): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(?string $email): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(?string $adresse): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoste(): ?\App\Entity\Poste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoste', []);

        return parent::getPoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoste(?\App\Entity\Poste $poste): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoste', [$poste]);

        return parent::setPoste($poste);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntreprise(): ?\App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntreprise', []);

        return parent::getEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntreprise(?\App\Entity\Entreprise $entreprise): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntreprise', [$entreprise]);

        return parent::setEntreprise($entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getConteneure(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConteneure', []);

        return parent::getConteneure();
    }

    /**
     * {@inheritDoc}
     */
    public function setConteneure(string $conteneure): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConteneure', [$conteneure]);

        return parent::setConteneure($conteneure);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(string $photo): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTravaillerPersonnels(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTravaillerPersonnels', []);

        return parent::getTravaillerPersonnels();
    }

    /**
     * {@inheritDoc}
     */
    public function addTravaillerPersonnel(\App\Entity\TravaillerPersonnel $travaillerPersonnel): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTravaillerPersonnel', [$travaillerPersonnel]);

        return parent::addTravaillerPersonnel($travaillerPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTravaillerPersonnel(\App\Entity\TravaillerPersonnel $travaillerPersonnel): \App\Entity\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTravaillerPersonnel', [$travaillerPersonnel]);

        return parent::removeTravaillerPersonnel($travaillerPersonnel);
    }

}
