<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWzC6hk6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWzC6hk6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWzC6hk6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWzC6hk6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWzC6hk6\App_KernelDevDebugContainer([
    'container.build_hash' => 'WzC6hk6',
    'container.build_id' => '53d75db1',
    'container.build_time' => 1587891035,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWzC6hk6');
